
all:
	$(MAKE) -C surfacelayer/dummyfortran
	$(MAKE) -C surfacelayer/dummyc
	$(MAKE) -C subsurface/dummyfortran
	$(MAKE) -C subsurface/dummyc
	$(MAKE) -C openwater/dummyfortran
	$(MAKE) -C openwater/dummyc
