
all:
	$(MAKE) -C surfacelayer/dummyfortran
	$(MAKE) -C surfacelayer/dummyc
	$(MAKE) -C subsurface/dummyfortran
	$(MAKE) -C subsurface/dummyc
	$(MAKE) -C openwater/dummyfortran
	$(MAKE) -C openwater/dummyc

clean:
	$(MAKE) clean -C surfacelayer/dummyfortran
	$(MAKE) clean -C surfacelayer/dummyc
	$(MAKE) clean -C subsurface/dummyfortran
	$(MAKE) clean -C subsurface/dummyc
	$(MAKE) clean -C openwater/dummyfortran
	$(MAKE) clean -C openwater/dummyc
